name: Build and upload bundle
on:
  release:
    types: [published]
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm clean-install
      - run: npm run build
      - run: ar czf age.tar.gz dist/
      - uses: actions/upload-artifact@v4
        with:
          name: age.tar.gz
          path: age.tar.gz
  upload:
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: age.tar.gz
      - run: gh release upload -R pajowu/typage "$VERSION" "age.tar.gz"
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ github.token }}
