name: Build and upload bundle
on:
  release:
    types: [published]
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm clean-install
      - run: npm run build
      - run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: age-build
          path: age-encryption-*.tgz
      - run: gh release upload -R pajowu/typage "$VERSION" age-encryption-*.tgz
        if: github.event_name == 'release'
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ github.token }}
